[package]
name = "dll"
version = "0.1.0"
authors = ["Kevin Darlington <kevin@outroot.com>"]

[lib]
name = "hook"
crate-type = ["cdylib"]

[dependencies]
sharedlib = "3.1"
winapi = "0.2"
libc = "0.2"
kernel32-sys = "0.2"
